------------------------------------------------------------
--
-- Setup.hs
-- Code sample accompanying topic 2.1.4 "Stack hints and tips"
-- See README.md for details
--
-- Fundamentals of Practical Haskell Programming
-- By Richard Cook
--
------------------------------------------------------------

