------------------------------------------------------------
--
-- Setup.hs
-- Code sample accompanying topic 2.3.1 "Package repositories"
-- See README.md for details
--
-- Fundamentals of Practical Haskell Programming
-- By Richard Cook
--
------------------------------------------------------------

