------------------------------------------------------------
--
-- Setup.hs
-- Code sample accompanying topic 2.1.3 "Stack in detail"
-- See README.md for details
--
-- Fundamentals of Practical Haskell Programming
-- By Richard Cook
--
------------------------------------------------------------

